LIB = imagine

INCLUDES = -I $(includedir)/newbase -I /usr/local/include/freetype2
CFLAGS = -DUNIX $(INCLUDES) -ansi -w2 -Werror -wd981,383,869,444,488,810

CC = /usr/local/intel/compiler70/ia32/bin/icc

# Common library compiling template

include ../../makefiles/makefile.lib

